theme: jekyll-theme-cayman
title: [Alan Huang]
description: ["Hello! I'm currently studying Computer Science at UC Irvine. I'm excited to see where my studies lead me, 
              and am interested in getting a feel for all kinds of programming jobs. Thanks for taking a look at my page!"]
